/* react */
import IdText from './IdText';

export default class UBanco {}
UBanco.bancoDoBrasil = new IdText(1, "001 - Banco do Brasil S.A.", null);
UBanco.LISTA = [
	IdText.VAZIO
	, UBanco.bancoDoBrasil
	, new IdText(999, "000 - Banco Bankpar S.A.")
	, new IdText(3, "003 - Banco da Amazônia S.A.", null)
	, new IdText(4, "004 - Banco do Nordeste do Brasil S.A.")
	, new IdText(5, "012 - Banco Standard de Investimentos S.A.")
	, new IdText(6, "014 - Natixis Brasil S.A. Banco Múltiplo")
	, new IdText(7, "019 - Banco Azteca do Brasil S.A.")
	, new IdText(8, "021 - BANESTES S.A. Banco do Estado do Espírito Santo")
	, new IdText(9, "024 - Banco de Pernambuco S.A. - BANDEPE")
	, new IdText(10, "025 - Banco Alfa S.A.")
	, new IdText(11, "029 - Banco Banerj S.A.")
	, new IdText(12, "031 - Banco Beg S.A.")
	, new IdText(13, "033 - Banco Santander (Brasil) S.A.")
	, new IdText(14, "036 - Banco Bradesco BBI S.A.")
	, new IdText(15, "037 - Banco do Estado do Pará S.A.")
	, new IdText(16, "039 - Banco do Estado do Piauí S.A. - BEP")
	, new IdText(17, "040 - Banco Cargill S.A.")
	, new IdText(18, "041 - Banco do Estado do Rio Grande do Sul S.A.")
	, new IdText(19, "044 - Banco BVA S.A.")
	, new IdText(20, "045 - Banco Opportunity S.A.")
	, new IdText(21, "047 - Banco do Estado de Sergipe S.A.")
	, new IdText(22, "062 - Hipercard Banco Múltiplo S.A.")
	, new IdText(23, "063 - Banco Ibi S.A. Banco Múltiplo")
	, new IdText(24, "064 - Goldman Sachs do Brasil Banco Múltiplo S.A.")
	, new IdText(25, "065 - Banco Bracce S.A.")
	, new IdText(26, "066 - Banco Morgan Stanley S.A.")
	, new IdText(27, "069 - BPN Brasil Banco Múltiplo S.A.")
	, new IdText(28, "070 - BRB - Banco de Brasília S.A.")
	, new IdText(29, "072 - Banco Rural Mais S.A.")
	, new IdText(30, "073 - BB Banco Popular do Brasil S.A.")
	, new IdText(31, "074 - Banco J. Safra S.A.")
	, new IdText(32, "075 - Banco CR2 S.A.")
	, new IdText(33, "076 - Banco KDB S.A.")
	, new IdText(34, "077-9 - Banco Intermedium S.A.")
	, new IdText(35, "078 - BES Investimento do Brasil S.A.-Banco de Investimento")
	, new IdText(36, "079 - JBS Banco S.A.")
	, new IdText(37, "081-7 - Concórdia Banco S.A.")
	, new IdText(38, "082-5 - Banco Topázio S.A.")
	, new IdText(39, "083-3 - Banco da China Brasil S.A.")
	, new IdText(40, "084 - Unicred Norte do Paraná")
	, new IdText(41, "085-x - Cooperativa Central de Crédito Urbano-CECRED")
	, new IdText(42, "086-8 - OBOE Crédito Financiamento e Investimento S.A.")
	, new IdText(43, "087-6 - Cooperativa Unicred Central Santa Catarina")
	, new IdText(44, "088-4 - Banco Randon S.A.")
	, new IdText(45, "089-2 - Cooperativa de Crédito Rural da Região de Mogiana")
	, new IdText(46, "090-2 - Cooperativa Central de Economia e Crédito Mutuo das Unicreds")
	, new IdText(47, "091-4 - Unicred Central do Rio Grande do Sul")
	, new IdText(48, "092-2 - Brickell S.A. Crédito, financiamento e Investimento")
	, new IdText(49, "094-2 - Banco Petra S.A.")
	, new IdText(50, "096 - Banco BM&F de Serviços de Liquidação e Custódia S.A")
	, new IdText(51, "097-3 - Cooperativa Central de Crédito Noroeste Brasileiro Ltda.")
	, new IdText(52, "098-1 - Credicorol Cooperativa de Crédito Rural")
	, new IdText(53, "099-x - Cooperativa Central de Economia e Credito Mutuo das Unicreds")
	, new IdText(54, "104 - Caixa Econômica Federal")
	, new IdText(55, "107 - Banco BBM S.A.")
	, new IdText(56, "168 - HSBC Finance (Brasil) S.A. - Banco Múltiplo")
	, new IdText(57, "184 - Banco Itaú BBA S.A.")
	, new IdText(58, "204 - Banco Bradesco Cartões S.A.")
	, new IdText(59, "208 - Banco BTG Pactual S.A.")
	, new IdText(60, "212 - Banco Matone S.A.")
	, new IdText(61, "213 - Banco Arbi S.A.")
	, new IdText(62, "214 - Banco Dibens S.A.")
	, new IdText(63, "215 - Banco Comercial e de Investimento Sudameris S.A.")
	, new IdText(64, "217 - Banco John Deere S.A.")
	, new IdText(65, "218 - Banco Bonsucesso S.A.")
	, new IdText(66, "222 - Banco Credit Agricole Brasil S.A.")
	, new IdText(67, "224 - Banco Fibra S.A.")
	, new IdText(68, "225 - Banco Brascan S.A.")
	, new IdText(69, "229 - Banco Cruzeiro do Sul S.A.")
	, new IdText(70, "230 - Unicard Banco Múltiplo S.A.")
	, new IdText(71, "233 - Banco GE Capital S.A.")
	, new IdText(72, "237 - Banco Bradesco S.A.")
	, new IdText(73, "241 - Banco Clássico S.A.")
	, new IdText(74, "243 - Banco Máxima S.A.")
	, new IdText(75, "246 - Banco ABC Brasil S.A.")
	, new IdText(76, "248 - Banco Boavista Interatlântico S.A.")
	, new IdText(77, "249 - Banco Investcred Unibanco S.A.")
	, new IdText(78, "250 - Banco Schahin S.A.")
	, new IdText(79, "254 - Paraná Banco S.A.")
	, new IdText(80, "263 - Banco Cacique S.A.")
	, new IdText(81, "265 - Banco Fator S.A.")
	, new IdText(82, "266 - Banco Cédula S.A.")
	, new IdText(83, "300 - Banco de La Nacion Argentina")
	, new IdText(84, "318 - Banco BMG S.A.")
	, new IdText(85, "320 - Banco Industrial e Comercial S.A.")
	, new IdText(86, "341 - Itaú Unibanco S.A.")
	, new IdText(87, "356 - Banco Real S.A.")
	, new IdText(88, "366 - Banco Société Générale Brasil S.A.")
	, new IdText(89, "370 - Banco WestLB do Brasil S.A.")
	, new IdText(90, "376 - Banco J. P. Morgan S.A.")
	, new IdText(91, "389 - Banco Mercantil do Brasil S.A.")
	, new IdText(92, "394 - Banco Bradesco Financiamentos S.A.")
	, new IdText(93, "399 - HSBC Bank Brasil S.A. - Banco Múltiplo")
	, new IdText(94, "409 - UNIBANCO - União de Bancos Brasileiros S.A.")
	, new IdText(95, "412 - Banco Capital S.A.")
	, new IdText(96, "422 - Banco Safra S.A.")
	, new IdText(97, "453 - Banco Rural S.A.")
	, new IdText(98, "456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.")
	, new IdText(99, "464 - Banco Sumitomo Mitsui Brasileiro S.A.")
	, new IdText(100, "473 - Banco Caixa Geral - Brasil S.A.")
	, new IdText(101, "477 - Citibank N.A.")
	, new IdText(102, "479 - Banco ItaúBank S.A")
	, new IdText(103, "487 - Deutsche Bank S.A. - Banco Alemão")
	, new IdText(104, "488 - JPMorgan Chase Bank")
	, new IdText(105, "492 - ING Bank N.V.")
	, new IdText(106, "494 - Banco de La Republica Oriental del Uruguay")
	, new IdText(107, "495 - Banco de La Provincia de Buenos Aires")
	, new IdText(108, "505 - Banco Credit Suisse (Brasil) S.A.")
	, new IdText(109, "600 - Banco Luso Brasileiro S.A.")
	, new IdText(110, "604 - Banco Industrial do Brasil S.A.")
	, new IdText(111, "610 - Banco VR S.A.")
	, new IdText(112, "611 - Banco Paulista S.A.")
	, new IdText(113, "612 - Banco Guanabara S.A.")
	, new IdText(114, "613 - Banco Pecúnia S.A.")
	, new IdText(115, "623 - Banco Panamericano S.A.")
	, new IdText(116, "626 - Banco Ficsa S.A.")
	, new IdText(117, "630 - Banco Intercap S.A.")
	, new IdText(118, "633 - Banco Rendimento S.A.")
	, new IdText(119, "634 - Banco Triângulo S.A.")
	, new IdText(120, "637 - Banco Sofisa S.A.")
	, new IdText(121, "638 - Banco Prosper S.A.")
	, new IdText(122, "641 - Banco Alvorada S.A.")
	, new IdText(123, "643 - Banco Pine S.A.")
	, new IdText(124, "652 - Itaú Unibanco Holding S.A.")
	, new IdText(125, "653 - Banco Indusval S.A.")
	, new IdText(126, "654 - Banco A.J.Renner S.A.")
	, new IdText(127, "655 - Banco Votorantim S.A.")
	, new IdText(128, "707 - Banco Daycoval S.A.")
	, new IdText(129, "719 - Banif-Banco Internacional do Funchal (Brasil)S.A.")
	, new IdText(130, "721 - Banco Credibel S.A.")
	, new IdText(131, "724 - Banco Porto Seguro S.A.")
	, new IdText(132, "734 - Banco Gerdau S.A.")
	, new IdText(133, "735 - Banco Pottencial S.A.")
	, new IdText(134, "738 - Banco Morada S.A.")
	, new IdText(135, "739 - Banco BGN S.A.")
	, new IdText(136, "740 - Banco Barclays S.A.")
	, new IdText(137, "741 - Banco Ribeirão Preto S.A.")
	, new IdText(138, "743 - Banco Semear S.A.")
	, new IdText(139, "744 - BankBoston N.A.")
	, new IdText(140, "745 - Banco Citibank S.A.")
	, new IdText(141, "746 - Banco Modal S.A.")
	, new IdText(142, "747 - Banco Rabobank International Brasil S.A.")
	, new IdText(143, "748 - Banco Cooperativo Sicredi S.A.")
	, new IdText(144, "749 - Banco Simples S.A.")
	, new IdText(145, "751 - Dresdner Bank Brasil S.A. - Banco Múltiplo")
	, new IdText(146, "752 - Banco BNP Paribas Brasil S.A.")
	, new IdText(147, "753 - NBC Bank Brasil S.A. - Banco Múltiplo")
	, new IdText(148, "755 - Bank of America Merrill Lynch Banco Múltiplo S.A.")
	, new IdText(149, "756 - Banco Cooperativo do Brasil S.A. - BANCOOB")
	, new IdText(150, "757 - Banco KEB do Brasil S.A.")
	, new IdText(151, "M03 - Banco Fiat S.A.")
	, new IdText(152, "M06 - Banco de Lage Landen Brasil S.A.")
	, new IdText(153, "M07 - Banco GMAC S.A.")
	, new IdText(154, "M08 - Banco Citicard S.A.")
	, new IdText(155, "M09 - Banco Itaucred Financiamentos S.A.")
	, new IdText(156, "M10 - Banco Moneo S.A.")
	, new IdText(157, "M11 - Banco IBM S.A.")
	, new IdText(158, "M12 - Banco Maxinvest S.A.")
	, new IdText(159, "M13 - Banco Tricury S.A.")
	, new IdText(160, "M14 - Banco Volkswagen S.A.")
	, new IdText(161, "M15 - Banco BRJ S.A.")
	, new IdText(162, "M16 - Banco Rodobens S.A.")
	, new IdText(163, "M17 - Banco Ourinvest S.A.")
	, new IdText(164, "M18 - Banco Ford S.A.")
	, new IdText(165, "M19 - Banco CNH Capital S.A.")
	, new IdText(166, "M20 - Banco Toyota do Brasil S.A.")
	, new IdText(167, "M21 - Banco Daimlerchrysler S.A.")
	, new IdText(168, "M22 - Banco Honda S.A.")
	, new IdText(169, "M23 - Banco Volvo (Brasil) S.A.")
	, new IdText(170, "M24 - Banco PSA Finance Brasil S.A.")
];
